using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Komento.Generators;

[Generator]
public sealed class KomentoGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var komentoJson = context.AdditionalTextsProvider
            .Where(f => string.Equals(
                Path.GetFileName(f.Path),
                "komento.json",
                StringComparison.OrdinalIgnoreCase));

        context.RegisterSourceOutput(komentoJson, (ctx, file) =>
        {
            var content = file.GetText()?.ToString();
            if (string.IsNullOrWhiteSpace(content)) return;

            var ids = ParseExperimentIds(content!);
            if (ids.Count == 0) return;

            ctx.AddSource("KomentoExperiments.g.cs",
                SourceText.From(GenerateSource(ids), Encoding.UTF8));
        });
    }

    private static List<string> ParseExperimentIds(string json)
    {
        var m = Regex.Match(json, "\"Experiments\"\\s*:\\s*\\[([^\\]]*)\\]");
        if (!m.Success) return new List<string>();

        return Regex.Matches(m.Groups[1].Value, "\"([^\"]+)\"")
            .Cast<Match>()
            .Select(x => x.Groups[1].Value)
            .Where(id => !string.IsNullOrWhiteSpace(id))
            .ToList();
    }

    private static string GenerateSource(List<string> ids)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System.Collections.Frozen;");
        sb.AppendLine();
        sb.AppendLine("public static class KomentoExperiments");
        sb.AppendLine("{");

        var idsArray = string.Join(", ", ids.Select(id => "\"" + id + "\""));
        sb.AppendLine("    public static readonly FrozenSet<string> AllIds =");
        sb.AppendLine("        new[] { " + idsArray + " }.ToFrozenSet();");

        foreach (var id in ids)
        {
            var className = ToPascalCase(id);
            sb.AppendLine();
            sb.AppendLine("    public static class " + className);
            sb.AppendLine("    {");
            sb.AppendLine("        public const string Id = \"" + id + "\";");
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string ToPascalCase(string id)
    {
        var sb = new StringBuilder();
        var capitalizeNext = true;
        foreach (var c in id)
        {
            if (c == '-' || c == '_' || c == ' ' || c == '.')
            {
                capitalizeNext = true;
            }
            else if (char.IsLetterOrDigit(c))
            {
                sb.Append(capitalizeNext ? char.ToUpperInvariant(c) : c);
                capitalizeNext = false;
            }
        }
        return sb.ToString();
    }
}
