<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.NATS.Net" />
    <PackageReference Include="Aspire.Npgsql" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="OpenFeature" />
  </ItemGroup>
  <ItemGroup>
    <AdditionalFiles Include="komento.json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Komento/Komento.csproj" />
    <ProjectReference Include="../../src/Komento.AspNetCore/Komento.AspNetCore.csproj" />
    <ProjectReference Include="../../src/Komento.OpenFeature/Komento.OpenFeature.csproj" />
    <ProjectReference Include="../../src/Komento.Generators/Komento.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
    <ProjectReference Include="../Komento.Sample.ServiceDefaults/Komento.Sample.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
